# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param synth.incrementalSynthesisCache D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/.Xil/Vivado-10648-DESKTOP-T0O4NS9/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.cache/wt [current_project]
set_property parent.project_path D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/doc/dds_256x8b_wave.coe
add_files d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/doc/dds_256x8b_wave2.coe
read_verilog -library xil_defaultlib {
  D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/new/ad_wave_rec.v
  D:/FPGA/ZYNQ_7010_FPGA/10_lcd_rgb_colorbar/lcd_rgb_colorbar.srcs/sources_1/new/clk_div.v
  D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/new/da_wave_send.v
  D:/FPGA/ZYNQ_7010_FPGA/8_ip_fifo/ip_fifo.srcs/sources_1/new/fifo_rd.v
  D:/FPGA/ZYNQ_7010_FPGA/8_ip_fifo/ip_fifo.srcs/sources_1/new/fifo_wr.v
  D:/FPGA/ZYNQ_7010_FPGA/10_lcd_rgb_colorbar/lcd_rgb_colorbar.srcs/sources_1/new/lcd_display.v
  D:/FPGA/ZYNQ_7010_FPGA/10_lcd_rgb_colorbar/lcd_rgb_colorbar.srcs/sources_1/new/lcd_driver.v
  D:/FPGA/ZYNQ_7010_FPGA/10_lcd_rgb_colorbar/lcd_rgb_colorbar.srcs/sources_1/new/lcd_rgb_colorbar.v
  D:/FPGA/ZYNQ_7010_FPGA/10_lcd_rgb_colorbar/lcd_rgb_colorbar.srcs/sources_1/new/rd_id.v
  D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/new/hs_ad_da.v
}
read_ip -quiet D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_0_ooc.xdc]

read_ip -quiet D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/rom_256x8b_1/rom_256x8b.xci
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/rom_256x8b_1/rom_256x8b_ooc.xdc]

read_ip -quiet D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_1/ila_1.xci
set_property used_in_synthesis false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]

read_ip -quiet D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_2/ila_2.xci
set_property used_in_synthesis false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_2/ila_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/constrs_1/new/hs_ad_da.xdc
set_property used_in_implementation false [get_files D:/FPGA/ZYNQ_7010_FPGA/18_hs_ad_da/hs_ad_da.srcs/constrs_1/new/hs_ad_da.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top hs_ad_da -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hs_ad_da.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hs_ad_da_utilization_synth.rpt -pb hs_ad_da_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
